before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
        #      - darwin
    ignore:
      - goos: windows
        goarch: arm64
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'
      - '^docker:'

dockers:
  - image_templates:
      - "ghcr.io/zekker6/traefik-hosts-generator:latest"
      - "ghcr.io/zekker6/traefik-hosts-generator:{{ .Tag }}"
