before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^example:'
      - '^docker:'

dockers:
  - image_templates:
#      - "zekker6/traefik-hosts-generator:latest"
#      - "zekker6/traefik-hosts-generator:{{ .Tag }}"
#      - "zekker6/traefik-hosts-generator:{{ .Tag }}-{{ .Env.GO_VERSION }}"
#      - "zekker6/traefik-hosts-generator:v{{ .Major }}"
      - "ghcr.io/zekker6/traefik-hosts-generator:latest"
      - "ghcr.io/zekker6/traefik-hosts-generator:{{ .Tag }}"